### ISSUE TITLE
templeting and preprocessing

### ISSUE THREAD

**Issue by Jay0007** [vuejs/vue-loader#1051]
why do we need templeting and preprocessing engine in vue

**Comment by LinusBorg** [comment]
Hello @Jay0007 

Thank your for your interest in this project.

However, your issue is a usage/support questions or discussions, and the issue tracker is reserved exclusively for bug reports and feature requests (as outlined in our [Contributing Guide](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md)).

We encourage you to ask it on the [forum ](http://forum.vuejs.org) , [Stack Overflow](http://stackoverflow.com/questions/tagged/vue.js) or on our [Discord chat](http://chat.vuejs.org) and are happy to help you out there.
