### ISSUE TITLE
Async loading routing, how to separate the CSS under the routing？

### ISSUE THREAD

**Issue by zhump** [vuejs/vue-loader#1068]
Async loading routing, how to separate the CSS under the routing？
like this
```
0.xxxx.js
0.xxxx.css
1.xxxx.js
1.xxxx.css
```

**Comment by LinusBorg** [comment]
Hello @zhump,

Thank your for your interest in this project.

However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests (as outlined in our [Contributing Guide](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md)).

We encourage you to ask it on the [forum ](http://forum.vuejs.org) , [Stack Overflow](http://stackoverflow.com/questions/tagged/vue.js) or on our [Discord chat](http://chat.vuejs.org) and are happy to help you out there.
