### ISSUE TITLE
Support Babel in template attributes

### ISSUE THREAD

**Issue by sjoerdvisscher** [vuejs/vue-loader#128]
A colleage did something like this: 

```
<div :class="{ [`at-index-${index}`]: true }">...</div>
```

which seemed to work fine, but only because Chrome supports this syntax already.

Only later when testing in Safari we found out Babel syntax is not supported in attributes. But it would be nice to have!

**Comment by yyx990803** [comment]
Indeed good to have - the problem is that Babel would transpile some short expressions to very verbose code (e.g. [this one](https://babeljs.io/repl/#?experimental=true&evaluate=false&loose=false&spec=false&code=var%20a%20%3D%20%7B%20%5B%60at-index-%24%7Bindex%7D%60%5D%3A%20true%20%7D)) and it wouldn't work inside directives because that's more than a single expression :(

Maybe we can support the dynamic key syntax as a special case, since this seems to be a pain point of current `:class` syntax.

**Comment by sjoerdvisscher** [comment]
The expression issue could be fixed with wrapping everything in a function, which gets executed immediately.

But maybe just a warning for now? Although I don't know how to detect Babel syntax properly.

There's a good alternative: 

```
<div class="at-index-{{index}}">...</div>
```

This doesn't work when the value `true` is an expression instead, but a dynamic class name which dynamically toggles as well seems to be rare.

**Comment by yyx990803** [comment]
Or you can use the array syntax: `<div :class="[ condition ? 'at-index-' + index : '' ]">`

**Comment by yyx990803** [comment]
This is now supported in ^9.5.0 via Buble.

**Comment by Akryum** [comment]
This code fails in Internet Explorer because bublé doesn't transpile arrow functions:

```html
<a v-for="letter of letters" :class="{active:typeData.letters.some(l => l.letter === letter)}" @click="scrollToLetter(letter)">{{ letter }}</a>
```

Why was [this](https://github.com/vuejs/vue-template-es2015-compiler/commit/16c0d2b0ddfd0280528b793261c44e785c44d7df) reverted?
