### ISSUE TITLE
Suggestion: partial definition tag

### ISSUE THREAD

**Issue by lazabogdan** [vuejs/vue-loader#134]
Would be nice to able to define component partials in a similar way we're defining the `template`, with a dedicated `<partial>` tag.

Feels wrong to have `template` code like this, defined in the `script` section, in the context of a `.vue` file:

![partial-tag](https://cloud.githubusercontent.com/assets/6580668/12346010/d0f1089e-bb58-11e5-8523-f3c78bfdabf0.png)

Instead of the above, we could do:

![partial-tag-suggestion-v2](https://cloud.githubusercontent.com/assets/6580668/12346185/b97071b2-bb5a-11e5-892b-d80ee0a3c1cc.png)

Which in my opinion, feels much better.

Or, since a partial is essentially a template, without introducing a new `partial` tag which might be confusing, maybe just add support for multiple `template` tags, and a `partial` property, something like:

##### Main template

```html
<template>
   <partial name="dropdown-area-content"></partial>
</template>
```

##### Partial template

```html
<template partial="dropdown-area-content">
    ...
</template>
```

**Comment by xsbear** [comment]
+1

**Comment by aninfeel** [comment]
+1
It's so awkward when template language is not html but something like jade.

**Comment by chbdetta** [comment]
+1

**Comment by miljan-aleksic** [comment]
As partials are getting deprecated in Vue 2 this suggestions is getting obsolete, but a more global solution could solve this and future needs. Using the same multiple tags but saving the results on a variable that could be used by the component declaration. Example:

```html
<template ref="Foo">
  HTML, Partial, etc.
</template>
<template ref="Bar">
  HTML, Partial, etc.
</template>
```

In the component script:

```js
export default {
  partials: {
    Foo
  },
  computed: {
    Bar: () => Bar
  }
}
```

Anyhow, would like to know your opinions about this, guys.

**Comment by yyx990803** [comment]
I'm sorry but this will not be supported.

1. If the partial is used only inside the same component, there's no reason for them to be partials. They should just be in the component's main template.

2. If the reason you want partials inside the component is simply because the template is getting so large, it's a sign that you are putting too much into the same component. Split it into more components.  Think in components, not partials.

3. Partials do not support scoped CSS.

4. Partials are going to be deprecated in 2.0.
