### ISSUE TITLE
Feature Request: Support targeting Chrome 41 used by Googlebot for crawling

### ISSUE THREAD

**Issue by atiqorin** [vuejs/vue-loader#1517]
### What problem does this feature solve?
Vue-loader currently does not support targeting below chrome 48. For users perspective many may argue that supporting below chrome 48 is not necessary. However Google still uses Chrome 41 to crawl. Our app wasn't showing any vue-components on Googlebots crawl. This was a show stopper for us. So I had to use babel preset env with plugins and shims to make the app show up on Googlebot. If vue-loader supported chrome 41 then a lot of other users who use vue-loader can enjoy less headache regarding SEO and crawling.

### What does the proposed API look like?
Should allow:
{
    loader: 'vue-loader',
       options: {
          transpileOptions: {
     target: { chrome: 41 },
    }
  }
 }

**Comment by posva** [comment]
what do you mean by _Vue-loader currently does not support targeting below chrome 48_, adding the chrome version to your browserlist that is taken into account by babel should be what you need

**Comment by atiqorin** [comment]
I see following error on my build:
when i provide the transpileOptions I put at the issue description. If I put chrome: 48 as target, no error.

Module build failed (from ./node_modules/vue-loader/lib/loaders/templateLoader.js):
Error: Support data exists for the following versions of chrome: 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63.

**Comment by sodatea** [comment]
FYI the error comes from here: https://github.com/yyx990803/buble/blob/f5996c9cdb2e61cb7dddf0f6c6f25d0f3f600055/src/support.js

And I don't think you should manually set `target` in `transpileOptions`. It's better to use babel for legacy browser support.

Buble is depended by `vue-template-es2015-compiler` for those goals:
1. strip `with` in production bundle
2. support for some common ES2015+ patterns in **template** code (and **only template**)

In the case that there's unsupported syntax left in the render function, it is very likely that there's also code with unsupported syntax in the script block. In that case you already need babel for transpilation, so no need to bother configuring buble.
Babel does a better job in supporting legacy browsers. We use buble here mainly because template compilation is a quite lightweight job so we need a lightweight & fast compiler.
