### ISSUE TITLE
slot's data-v-* scope is not set correctly when there is a <div class="*"> immediately after the <slot>

### ISSUE THREAD

**Issue by senku** [vuejs/vue-loader#1598]
### Version
15.7.1

### Reproduction link
[https://codesandbox.io/s/vue-loader-slot-and-scoped-bug-0s6xo](https://codesandbox.io/s/vue-loader-slot-and-scoped-bug-0s6xo)

### Steps to reproduce
Open codesandbox and click "Test" button

### What is expected?
All displayed text is red (apply `.colorful` class).

### What is actually happening?
`BuggyComponent` with `v-if` pattern is black.

---
- Child component have `<div class="...">` immediately after `<slot>`
  - Not happen when not `<div>` element
  - Not happen when `<div>` have no class
  - Not happen when not immediately after
- Parent component set top level element what  have `v-if`
  - Not happen when use `v-show`

**Comment by LinusBorg** [comment]
This is only indirectly related to scoped styles.

The underlying cause is DOM element re-use, which Vue tries to do whenever you add/remove elements.

i.e.:

```html
<div v-if="show" class="a" />

<div v-else class="b" />
```

Toggling `show` will not result in the first `div` being destroyed and a second one being created - it only results in the class on the same `div` being switched.

It's in this process that the data-v attribute from the parent gets lost somehow.

So  if we can solve this issue at all, it has to be done in Vue core, in the diffing & patching phase of the virtualdom.

For now, as a quick fix, you can assign a `key` to the dynamic content:

```html
<buggy-component>
  <div class="colorful" v-if="show" key="not-buggy-anymore">
    NG
  </div>
</buggy-component>
```

and consider re-opening this issue in Vue core (with a link back here)

**Comment by senku** [comment]
Thank you for explaining.

so I checked the issue of Vue core and I think it is similar to vuejs/vue/issues/10416 .
If this issue does not fix my problem, I will open a new issue at Vue core.

// I did a little bit of test, and found that the attribute of `div` need not be `class`.
