### ISSUE TITLE
Cannot read property 'styles' of undefined

### ISSUE THREAD

**Issue by candisecandise** [vuejs/vue-loader#1972]
### Version
16.8.3

### Steps to reproduce
I wanted to create a vue project with webpack.
I install vue@2, version is 2.7.0, but I install the lastest vue-loader, version is 17.0.0.
Then I ran `webpack-dev-server --mode development`, I got an error:
```
ERROR in ./src/App.vue
Module build failed (from ./node_modules/vue-loader/dist/index.js):
TypeError: Cannot read property 'styles' of undefined
    at Object.loader (/Users/admin/xxx/node_modules/vue-loader/dist/index.js:70:34)
 @ ./src/main.js 2:0-28 6:17-20
```
Is it vue@2 cannot be used with vue-loader@17?

### What is actually happening?
My project ran failed.

Thanks~

**Comment by bpossolo** [comment]
@candisecandise I'm experiencing this same thing as well using
- vue 2.7.0
- vue-loader 16.8.3
- typescript 4.7.4
- sass-loader 11.0.1
- css-loader 5.2.4

I removed my dependency on vue-template-compiler as mentioned in [step 2 of the upgrade guide](https://blog.vuejs.org/posts/vue-2-7-naruto.html).

here is my webpack config scss loader chain
```
{
  test: /\.scss$/,
  use: [
    'vue-style-loader',
    'css-loader',
    'sass-loader',
  ]
}
```

I wouldn't recommend using vue-loader 17 because the [changelog](https://github.com/vuejs/vue-loader/blob/next/CHANGELOG.md#1700-2021-12-12) says it requires vue 3

**Comment by bpossolo** [comment]
I tried downgrading to some earlier versions of vue-loader:
- 16.8.3
- 16.8.2
- 16.8.1
- 16.8.0
- 16.7.1

none of them work with vue 2.7.0

**Comment by bpossolo** [comment]
@yyx990803 it appears this issue may actually be valid however it got auto-closed by the bot...

**Comment by bpossolo** [comment]
@candisecandise I managed to get vue 2.7.0 to work with vue-loader 15.10.0  🎉
I also no longer have explicit dependency on vue-template-compiler in my package.json fwiw

**Comment by bpossolo** [comment]
Here is the upgrade guide/post

https://blog.vuejs.org/posts/vue-2-7-naruto.html

i can’t remember if I found it on the VueJS Twitter account or if it was directly on the vue blog.

**Comment by candisecandise** [comment]
> Here is the upgrade guide/post
> 
> https://blog.vuejs.org/posts/vue-2-7-naruto.html
> 
> i can’t remember if I found it on the VueJS Twitter account or if it was directly on the vue blog.

@bpossolo Got it, thank you again~

**Comment by B-o0O** [comment]
thank you guys
