### ISSUE TITLE
[Error] cannot find vue/compiler-sfc when using yarn workspace and lerna to install node_modules. 

### ISSUE THREAD

**Issue by radiorz** [vuejs/vue-loader#2031]
# depend: 
```
"@vue/compiler-sfc": "^3.2.47",
"vue-loader": "^17.0.1",
 "webpack": "^5.76.1",
```
# Try: 

- user `lerna bootstrap` to install node_modules,
- and try to run 
```
yarn workspace vue3 build
```
and came out error
![image](https://user-images.githubusercontent.com/24271959/225202904-55738cdb-4502-475b-9735-568bed618def.png)
# fix: 
just copy the `vue/compiler-sfc` in  child project's node_modules to the root's node_modules and it works fine.

# demo :

https://github.com/radiorz/webpack-demo

**Comment by heywhy** [comment]
I'm also facing this same issue because my project does not need `vue` to work. while looking at the vue-loader project I found this

https://github.com/vuejs/vue-loader/blob/1b1a195612f885a8dec3f371edf1cb8b35d341e4/src/index.ts#L8

the above is an opposite of

https://github.com/vuejs/vue-loader/blob/1b1a195612f885a8dec3f371edf1cb8b35d341e4/src/compiler.ts#L9-L25

import from `vue/sfc-compiler` should be replaced with `./compiler`
