### ISSUE TITLE
v17.3 breaks v-bind

### ISSUE THREAD

**Issue by morganarnel** [vuejs/vue-loader#2061]
I've found that after updating to version 17.3 any usage of `v-bind(...)` within in-component styling is broken. The CSS variable is correctly applied to the parent element in the DOM but the actual `v-bind(...)` is not replaced (see screenshot).

![image](https://github.com/vuejs/vue-loader/assets/84181964/84f2b04d-408e-47c6-b373-cd02484c1fba)

Reverting to 17.0 fixed this issue.

Vue Version: 3.3.4
Sass Loader Version: 13.3.2

**Comment by sodatea** [comment]
Could you please provide a minimal reproduction of this issue?

**Comment by amagne1** [comment]
I have the same issue. 

I think this is due to this feature :  #2053 

When you use v-bind inside a normal style (unscoped) like this :
<style lang="scss">
--my-css-var: v-bind(color);
</style>

If I add "scoped" to style, it's working (except I need this style not scoped :p )

You'll have the problem.
Reverting to 17.2.2 fixed this issue.
