### ISSUE TITLE
Coffee coverage

### ISSUE THREAD

**Issue by aristidesfl** [vuejs/vue-loader#329]
Which loader to use in order to get coffescript code coverage with .vue files?

**Comment by LinusBorg** [comment]
Hello @aristidesfl 

Thank your for your interest in this project.

However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests.

We encourage you to ask it on the [forum ](http://forum.vuejs.org) or on [gitter](http://gitter.im/vuejs/vue).

**Comment by aristidesfl** [comment]
For sure. It might be interesting when we sort this out to include coffee-coverage in the template right. Or at least in a separate branch?
