### ISSUE TITLE
[vue-loader@next] Export default constructor does not work

### ISSUE THREAD

**Issue by HerringtonDarkholme** [vuejs/vue-loader#340]
Version:

vue-loader@9.4.2

Repro:

https://github.com/HerringtonDarkholme/vue-loader-test/tree/constructor

```bash
npm install && ./node_modules/.bin/webpack && python3 -m http.server
```

Expected:

Exported constructor should work according to the doc.

Actual: 

Vue complains `Failed to mount component: template or render function not defined. (found in root instance)`

Problem:
`typeof __vue_modules__.default === 'object'` breaks exported constructors.

Though exported constructor is not recommended, but it is the only way I can find to cooperate with class component library...

**Comment by ktsn** [comment]
Thanks for filing this issue! I already sent PR (#341).

FYI: You should use standalone build to use html template. To adapt runtime build, use render option instead of writing html.

```js
new Vue({
  el: '#app',
  render: h => h('nani'),
  components: {
    'nani': require('../components/nani.vue')
  }
})
```

For more info, please see https://github.com/vuejs/vue/wiki/Vue-2.0-RC-Starter-Resources#standalone-vs-runtime-builds

**Comment by HerringtonDarkholme** [comment]
Thanks for mentioning that!
