### ISSUE TITLE
Inline load SVG inside Vue templates

### ISSUE THREAD

**Issue by ErickPetru** [vuejs/vue-loader#358]
Inline loading SVG inside HTML is really useful for styling and animations. I'm trying to make https://github.com/asnowwolf/markup-inline-loader work with vue-loader, but I'm not sure about how to configure it. Is it possible?

**Comment by BrainBacon** [comment]
@ErickPetru I've come up with a partial solution for my own project. The gist is to load the SVG into a simple component via a prop through webpack.

`glyph.vue`:
```vue
<style lang="sass">
    .glyph-container
        height: 100%
        width: 100%
</style>
<template lang="pug">
    .glyph-container(v-once v-html="src")
</template>
<script>
    module.exports = {
        props: ['src']
    };
</script>
```

Require your svg in a component scoped to your view:
`app.js`:
```js
let Vue = require('vue');

let vm = new Vue({
    data: () => ({
        mysvgdata: require('./mysvg.svg')
    })
});
Vue.component('c-glyph', require('./glyph.vue'));

vm.$mount('#root');

module.exports = vm;
```

Use it like this in your templates:
`mytemplate.pug`:
```pug
c-glyph(:src="mysvgdata")
```

You'll need to use a loader like [svg-inline-loader](https://github.com/sairion/svg-inline-loader)

### Pros:
 - This will only include the SVG in your packed JavaScript once, so you can use the same SVG in multiple locations without worrying about bloating your output too much.
 - The reference to your SVG is loaded inside of a component that is responsible for your view, so you don't have to maintain a centralized library of all of the svgs you use.
 - You can include SVG files directly output from graphic design software.

### Cons:
 - This bypasses Vue's rendering engine, so you won't be able to use scoped CSS see #359

**Comment by LinusBorg** [comment]
Hello ..

Thank your for your interest in this project.

However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests.

We encourage you to ask it on the [forum ](http://forum.vuejs.org) or on [gitter](http://gitter.im/vuejs/vue).

**Comment by ErickPetru** [comment]
@LinusBorg, sorry but I think **it's really a feature request**. As shown in the `markup-inline-loader` documentation, it could work along with other loaders. Example with `html-loader`:

    {
      test: /\.html$/,
      loader: 'html!markup-inline'
    }

But with `vue-loader`, it doesn't works:

    {
      test: /\.vue$/,
      loader: 'vue!markup-inline'
    }

**Comment by LinusBorg** [comment]
...because you have to tell vue-loader that this loader should be used for the HTML part of the component (not `script` or `style`).

http://vue-loader.vuejs.org/en/options.html
```js
vue: {
  loaders: {
    html: 'html!markup-inline'
  }
}
```


Further information through the forums. I'm not trying to make your life hard but we try to seperate work on github form support on the forums. Otherwise support-issue notificatiojn clog up our timeline and the actual work on the codebase becomes much harder,
