### ISSUE TITLE
lazy loading issue: Click 4 router-links in turn, router-view can render all the pages first time, but click all the links again it router-view does not render. 

### ISSUE THREAD

**Issue by kcmvp** [vuejs/vue-loader#368]
I raised this issue(https://github.com/vuejs/vue-router/issues/673) in vue-router and it's confirmed a vue-loader issue by @fnlctrl.

Here is the source to reproduce this issue https://github.com/kcheng-mvp/jkf/tree/vue-route2,

If I used **import** syntax instead of **lazy loading** then it works well.

https://github.com/kcheng-mvp/jkf/tree/use-import

Steps to reproduce this issue.

1: check out the source code from https://github.com/kcheng-mvp/jkf/tree/vue-route2
2: npm run dev
3: click the links in turn. the page is rendered successfully.
4: re-click the links again. you will find the page don't render.

**Comment by MervynFang** [comment]
same issue when i update to `2.1.0-beta.25`, `vue-loader@9.7.0`, `vue-router@2.0.1`, everthing work well in webpack 1.13.2

**Comment by MervynFang** [comment]
@kcheng-mvp I dont know whether if you solve the problem. It's due to require.ensure and AMD require is now always async, even if the chunk was already loaded. So change to `System.import` can solve it. You can see [What's new in webpack 2](https://gist.github.com/sokra/27b24881210b56bbaff7) and [lazy-loading demo](https://github.com/vuejs/vue-router/blob/84c0be69ca9962bf90857823aeae20a0047fef49/examples/lazy-loading/app.js). Thanks!
