### ISSUE TITLE
example's "sass" should be "scss"

### ISSUE THREAD

**Issue by bestian** [vuejs/vue-loader#376]
code like :
`<style lang="sass" scoped>
$c: #42b983;
h1 {
  color: $c;
}
</style>`

will not work because it's SCSS, not SASS.

**Comment by LinusBorg** [comment]
IT will work, because vue-loader will infer the loader-name to use from the `lang` attribute, and the loader is called [`sass-loader`](https://github.com/jtangelder/sass-loader), not scss-loader.

To use `lang="scss"`, you actually have to configure vue-loader like this:
```
vue: {
  loaders: {
    scss: 'style!css!sass'
  }
}
```

**Comment by luveti** [comment]
Both Atom and IntelliJ IDEA's vue plugins incorrectly highlight components style tags who contain lang="sass", despite writing SCSS code in the tags body.

Is there a good place we could add @LinusBorg's vue-loader configuration in the documentation?

I figure since this project is loader agnostic, we probably don't want to note this on the main README.md.

**Comment by LinusBorg** [comment]
> Both Atom and IntelliJ IDEA's vue plugins incorrectly highlight components style tags who contain lang="sass", despite writing SCSS code in the tags body.

the official vue-cli webpack template is already appropriately configured, so this won't happen.

> is there a good place we could add @LinusBorg's vue-loader configuration in the documentation?

Probably on [this page](https://vue-loader.vuejs.org/en/configurations/pre-processors.html)

I'll add a new issue.
