### ISSUE TITLE
How to control the injected app.js script location in the DOM?

### ISSUE THREAD

**Issue by KrishnaPG** [vuejs/vue-loader#407]
I am using the vue-loader with the webpack template.

I have to use an external JS file from CDN that need to be run **after** the tags / components have all been mounted. This requires me to put the `<script src="//cdnjs.com/external.js">` *after* the injected the `app.js` in the `index.html` page

But it looks like the generated `app.js` is being injected at the end. How to overcome this situation? 

And I have some JS files (once again, from CDN) that need to be run *before* the injected `app.js`.

Ideally,
````
 <script src='//cdnjs.com/run-before.js'></script>
 <script src=' app.js'> </script>     <-- app.js should be injected here
 <script src='//cdnjs.com/run-after.js'></script>
````

I do not want to loose the CDN advantage - but the order is important, since the events need to be hooked for elements once they are expanded / mounted correctly into DOM. 

Please help.

**Comment by yyx990803** [comment]
Update the `html-webpack-plugin` config per its docs: https://github.com/vuejs-templates/webpack/blob/master/template/build/webpack.dev.conf.js#L27-L32 (also do this for prod).

Also, 1. this is an issue related to the webpack template, so you should be opening issue there instead of here; 2. If you can, prefer asking questions on the forums. Issues are reserved for bugs.
