### ISSUE TITLE
Failed to mount component: template or render function not defined.  (found in component <input-tag>

### ISSUE THREAD

**Issue by matiastucci** [vuejs/vue-loader#438]
I'm making a Vue 2 component. But when I `npm link` it in other project and import it, I'm seeing this:

`Failed to mount component: template or render function not defined. 
(found in component <input-tag>)`

Here is my repo: https://github.com/matiastucci/vue-input-tag/tree/wtf and this is my [webpack.prod.conf.js](https://github.com/matiastucci/vue-input-tag/blob/wtf/build/webpack.prod.conf.js)

Also, I saw some answers saying that I need a vue alias pointing to dist and I already [have it](https://github.com/matiastucci/vue-input-tag/blob/wtf/build/webpack.base.conf.js#L26).

I didn't want to create an issue here but I've already posted in the Vue slack and [forum](http://forum.vuejs.org/t/vue-2-failed-to-mount-component-template-or-render-function-not-defined/2306) and in [SO](http://stackoverflow.com/questions/40329144/vue-js-2-0-failed-to-mount-component-template-or-render-function-not-defined) but I still don't know what's going on. Maybe here someone can help me :)

Thanks!

**Comment by LinusBorg** [comment]
How do you use/import this component in that other project? Do you use the built version form /dist? What does that built file look like?

**Comment by matiastucci** [comment]
@LinusBorg I generated a Vue 2 project using the CLI and the webpack template with the standalone build. And I'm importing the component doing: `import InputTag from 'vue-input-tag'`

**Comment by LinusBorg** [comment]
could you add the built file to the branch? can't build your projet right now?

**Comment by matiastucci** [comment]
sure, I just added the `dist` folder to the repo (https://github.com/matiastucci/vue-input-tag/tree/wtf/dist)

**Comment by LinusBorg** [comment]
...maybe not the minified version? :-P

**Comment by matiastucci** [comment]
oops, sorry haha. Here: https://gist.github.com/matiastucci/653615d7dd38f38739f966f76ada7c60

**Comment by LinusBorg** [comment]
https://webpack.github.io/docs/configuration.html#output-library

**Comment by LinusBorg** [comment]
Ah, I guess the problem is that you don't compile our component as a library. 

So your resulting file is not just the module, but a whole webpack runtime (which normally starts your app).

You would have to let webpack know that it should only export the component as a module, and not add the whole webpack runtime.

See docs: 

https://webpack.github.io/docs/configuration.html#output-library

**Comment by matiastucci** [comment]
I've already tried that, but I have the same problem.
I just tried again and updated the `webpack.prod.conf.js` file and the `dist` folder with this new output.

<img width="1279" alt="screen shot 2016-11-03 at 7 56 17 pm" src="https://cloud.githubusercontent.com/assets/3856355/19966760/d200641c-a1ff-11e6-9c5b-34fd7f7f36cd.png">

**Comment by LinusBorg** [comment]
what does the resulting file look like with those settings?

**Comment by matiastucci** [comment]
I updated it in `dist`: https://github.com/matiastucci/vue-input-tag/blob/wtf/dist/static/js/vue-input-tag.js

**Comment by matiastucci** [comment]
Any ideas? I couldn't get this to work yet. Thanks!

**Comment by LinusBorg** [comment]
Can't spot anything right now. Would have to 1. clone the repo and 2. reporduce the npom link to check this out. 

May find time on the weekend, not today.

**Comment by LinusBorg** [comment]
Can't spot anything right now. Would have to 1. clone the repo and 2. reporduce the npom link to check this out. 

May find time on the weekend, not today.

**Comment by LinusBorg** [comment]
Can't spot anything right now. Would have to 1. clone the repo and 2. reporduce the npom link to check this out. 

May find time on the weekend, not today.

**Comment by LinusBorg** [comment]
Oh, one thing I found: 

https://github.com/matiastucci/vue-input-tag/blob/wtf/build/webpack.prod.conf.js#L20

this should probably read: 

`library: utils.assetsPath('js/vue-input-tag.js'),`

**Comment by LinusBorg** [comment]
Oh, one thing I found: 

https://github.com/matiastucci/vue-input-tag/blob/wtf/build/webpack.prod.conf.js#L20

this should probably read: 

`library: utils.assetsPath('js/vue-input-tag.js'),`

**Comment by matiastucci** [comment]
ok, I'll try those changes and let you know. Thanks for the help!

**Comment by matiastucci** [comment]
sigh, I tried but is the same. I updated the repo.

I hope you can check it in the weekend. Thanks!

**Comment by matiastucci** [comment]
Did you have any chance?

**Comment by LinusBorg** [comment]
Sorry, haven't had access to my dev machine this weekend, family affairs. Hope to get it done tomorrow evening.

**Comment by matiastucci** [comment]
Sorry to bother you again, I just don't want you to forget. I would really appreciate if one of these days you can check it. Thanks :)

**Comment by LinusBorg** [comment]
Hey, so I started looking into this. I think I found the reason that it breaks, but don't know the solution yet.

So it has nothing to do with npm link, as was to be exüected.

* The build process somehow adds "use strict" to every module (it activates Javascript's "strict mode").
* in strict mode, you cannot do/use somethings. Among those: the `with` keyword.
* Vue uses that for its render functions though.

**Suspect 1**: Webpack.
Webpack 2 does add strict mode when you use `import` instead of `require()`. but 1.) you used Webpack 1, and 2.) changing all `import`s to `requirce` (inlcuding in my other test project to which I npm-link'ed your repo).

**Suspect 2**: Babel. 
Babel's `transform-es2015-modules-commonjs` plugin, which is part of the `es2015` babel preset, adds strict mode. But according to its [docs](https://babeljs.io/docs/plugins/transform-es2015-modules-commonjs/), we should be able to dectivate strict mode:

```json
["transform-es2015-modules-commonjs", {
      "strict": false,
    }]
```

But that didn't work so far. Still digging, stay tuned.

Btw importing the .vue file directly works fine. So it's something in the build chain that's screwing up.

Btw the problem with `with` is known and in the works: vuejs/vue#4115

**Comment by LinusBorg** [comment]
@matiastucci hey, can you clean out your npm-modules folder an re-install everything, with latest versions? Evan updated a vue-loader dependency that should solve this:

https://github.com/vuejs/vue-template-es2015-compiler/commit/37d08b304e6e7a6af010fd641597f5c3f5012f2c

**Comment by matiastucci** [comment]
I just did but I'm seeing the same thing :/

I pushed the changes to the repo

**Comment by LinusBorg** [comment]
Jesus you are a tough case ...

**Comment by matiastucci** [comment]
😬

I was pretty sure that was going to fix it. [This](https://github.com/matiastucci/vue-input-tag/blob/wtf/dist/static/js/vue-input-tag.js) is the new build.

**Comment by matiastucci** [comment]
well, I gave up. I published it and I'm exporting my `.vue` file as my `main`. I'll close this for now. Thanks for the help!
