### ISSUE TITLE
What's the difference between `scoped` and `module`?

### ISSUE THREAD

**Issue by octref** [vuejs/vue-loader#448]
AFAIK `module` uses css modules which also makes the styles locally scoped.

So what's the different of them? When should I use `module` over `scoped`?

**Comment by PowerfulPony** [comment]
* scope
Adds an attribute to the component identifier, as well as all the child components, as it adds a dependency on this attribute styles

It simulates classic `scope` where child elements, and parent can be to use the same classes, but can not use classes other components are not included in the zone of visibility.

* module as css-modules https://github.com/css-modules/css-modules
Completely isolates style classes, which prevents their use in other components (not intentionally)

**Comment by LinusBorg** [comment]
Thank your for your interest in this project. I hope @PowerfulPony's explanation was helpful.

Anyways, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests.

We encourage you to ask it on the [forum ](http://forum.vuejs.org) , [Stack Overflow](http://stackoverflow.com/questions/tagged/vue.js) or on [gitter](http://gitter.im/vuejs/vue) and are happy to help you out there.
