### ISSUE TITLE
Issue with resolving underscore methods in v-bind directive

### ISSUE THREAD

**Issue by ajanes93** [vuejs/vue-loader#476]
I have reproduced the issue in this repo [https://github.com/ajanes93/vue-webpack-underscore-issue](url)  see the checkbox input in the template for the Hello component.

when using v-bind to a html attribute I used to be able to call underscore methods directly like this;

```<input type="checkbox" v-bind:checked="_.contains([1,2,3,4], 1)">```

This no longer works and it throws the following error in the console: 

> "TypeError: Cannot read property 'contains' of undefined(…)"

I am using the vue-cli webpack template and I have declared underscore globally, the underscore method works fine if I call from within a computed property for example, so this a vue-loader issue I think.

Seems to work fine when using vue-loader 9.3.0

**Comment by ajanes93** [comment]
I think I worked it out.  Looking at the release notes for 9.4.0;

> "A subset of ES2015 features are now supported inside templates (requires vue@^2.0.0-rc.3):"

to fix my example above you just need to wrap the method in `  so the below will work in 9.4+

```<input type="checkbox" v-bind:checked="`_.contains([1,2,3,4], 1)`">```

**Comment by LinusBorg** [comment]
Uhm. No idea how that could have solved your problem ... now the function is not exectued as it's simply a string.

**Comment by ajanes93** [comment]
So I took the idea from the example given on the 9.4.0 release notes:

``` 
<!-- before -->
<a :href="'http://' + url + '/' + id">

<!-- after -->
<a :href="`http://${url}/${id}`">
```
wrapping the method in grave accents does fix the issue for me, I'm not sure why but it works

**Comment by ajanes93** [comment]
I take that back, you are correct, I think I misunderstood the release notes.

**Comment by LinusBorg** [comment]
Okay, to partly correct myself and get a little bit more technical:

Right now I assume that this is a side-effect of [this commit](https://github.com/vuejs/vue-template-es2015-compiler/commit/37d08b304e6e7a6af010fd641597f5c3f5012f2c) in vue-template-es2015-compiler, which removes with {} from render function. 

*Sidenote: This is crucial to keep compiled components working as ES6 modules, since those - by their specification - are always run in strict mode, and `with {}` is not allowed in strict mode.

I assume that he  transform used to achieve this, transforms your statement like this:
```javascript
// before
with(this) {
  // ...other code of the render function generated from the template by Vue
  _.contains([1,2,3,4], 1)
}

// after
  this._.contains([1,2,3,4], 1)
````

AFAIK it was always suggested to not access global entities from templates, event hough it seems this worked in your case and had no side-effects.

A quick solution would be to add `_` to all components as a prototype method instead of a global:

```javascript
import _ from 'underscore'
Vue.prototype._ = _
```
has the added benefit of keeping the global namespace clean.

/ping @yyx990803 I think this needs further investigation? Can we adjust the tranform to prevent cases like this? I don't think so.

**Comment by yyx990803** [comment]
This is expected. If you are using the dev build in Chrome it should have warned you against accessing `_` which is not found on the Vue instance.
