### ISSUE TITLE
How to "connect" two sass files, one of which is variables and another one being external module?

### ISSUE THREAD

**Issue by OriginalEXE** [vuejs/vue-loader#514]
Hello,

I want to use https://github.com/colourgarden/avalanche in my project, and I can easily do that by adding `<style src="normalize.css/normalize.css" lang="scss"></style>` in my .vue file. However, that file requires some prior configuration, so how and I supposed to include my custom .scss file which contains said configuration?

Is the only way to do this using `@import '../node_modules/avalanche-css/avalanche';` inside my `<style lang="scss"></style>` tags?

**Comment by LinusBorg** [comment]
Hello @OriginalEXE,

Thank your for your interest in this project.

However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests (as outlined in our [Contributing Guide](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md)).

We encourage you to ask it on the [forum ](http://forum.vuejs.org) , [Stack Overflow](http://stackoverflow.com/questions/tagged/vue.js) or on [gitter](http://gitter.im/vuejs/vue) and are happy to help you out there.
