### ISSUE TITLE
Webpack vue loader, test production with different env

### ISSUE THREAD

**Issue by adyz** [vuejs/vue-loader#610]
I noticed that you recommend setting the `process.env.NODE_ENV` to `production`:

> Use Webpack’s DefinePlugin to indicate a production environment, so that warning blocks can be automatically dropped by UglifyJS during minification.

Is there any way to test the production version of vue without changing the env in "production" because I have a `preproduction` and that I would like to test before I push to the real production and that needs to be the same as the production, except that the name is different and on my "prebuild" end I have some different file paths.

Thanks

**Comment by LinusBorg** [comment]
Hello @adyz

Thank your for your interest in this project.

However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests (as outlined in our [Contributing Guide](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md)).

We encourage you to ask it on the [forum ](http://forum.vuejs.org) , [Stack Overflow](http://stackoverflow.com/questions/tagged/vue.js) or on [gitter](http://gitter.im/vuejs/vue) and are happy to help you out there.
