### ISSUE TITLE
increate uniqueness of gen-id

### ISSUE THREAD

**Issue by morficus** [vuejs/vue-loader#645]
(related to #371)
Currently, [gen-id](https://github.com/vuejs/vue-loader/blob/master/lib/gen-id.js) runs the modules full file path through hash-sum to generate a unique value.

Using this method there is still a good possibility that the generated hash is not unique across different code bases (especially in instances where a CI tool is used to check different repos to the same target dir). 

For this reason, I would like to propose that `Date.now()` + file path be used for generating the component hash.

```javascript
  return cache[file] || (cache[file] = hash(file + Date.now()))

```

This would greatly increase the uniqueness of the generated module ID.

**Comment by yyx990803** [comment]
One thing is that we want the hash to be consistent across builds so that your CSS doesn't get a new chunk hash on every build (which breaks caching). In the latest version, the hash is generated from the file path relative from your project directory (where the root directory is also included).

I guess a better solution is to add a `hashKey` option where you can add a consistent unique key to the hash instead of `Date.now()`.
