### ISSUE TITLE
Recommendation: Change element order in example to <style> <template> <script>

### ISSUE THREAD

**Issue by BenRomberg** [vuejs/vue-loader#67]
I'd recommend to change the order of the example on https://github.com/vuejs/vue-loader from `<template> <script> <style>` to `<style> <template> <script>`. It would be in line with http://vuejs.org/guide/application.html and is also easier to work with, as both `<style>` and `<script>` are working with the `<template>` section of a .vue file. If you have `<template>` on the top and `<style>` on the bottom, you always have to jump over `<script>` if you're working on styling the template.

I've only realized this just now and am starting to change the orders of all of my .vue files, after having originally started with the order given in the example.

**Comment by yyx990803** [comment]
This is really up to the developer to decide what's best for them - I personally started with the `<style>` first order, but later on went `<style>` last because when a component has say 60+ lines of style, you'd have to scroll down a whole page to see the template and code every time you open it. I just prefer seeing the template and logic first when I look at a component, and it's really a personal preference.
