### ISSUE TITLE
Vue loader + posthtml 

### ISSUE THREAD

**Issue by edDimensi** [vuejs/vue-loader#695]
Hi. My low level of knowledge of English and webpack do not allow to solve this task. How to run posthtml together with a vue loader? In advance thanks for the answer.

**Comment by LinusBorg** [comment]
Hello @edDimensi 

Thank your for your interest in this project.

However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests (as outlined in our [Contributing Guide](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md)).

We encourage you to ask it on the [forum ](http://forum.vuejs.org) , [Stack Overflow](http://stackoverflow.com/questions/tagged/vue.js) or on [gitter](http://gitter.im/vuejs/vue) and are happy to help you out there.
