### ISSUE TITLE
img srcset compiler error.

### ISSUE THREAD

**Issue by zhe-he** [vuejs/vue-loader#701]
when i use 
`<img src="../images/card1.png" srcset="../images/card1@2x.png 2x,../images/card1@3x.png 3x" />`
in .vue.
it will be compiled
`<img src="dist/images/card1.png" srcset="../images/card1@2x.png 2x,../images/card1@3x.png 3x" />`.
It's not a correct thing to do actually.It should be
`<img src="dist/images/card1.png" srcset="dist/images/card1@2x.png 2x,dist/images/card1@3x.png 3x" />`.

Can add srcset compiler？

**Comment by dfdgsdfg** [comment]
Check this out.

https://github.com/vuejs-templates/webpack/issues/396

**Comment by kazupon** [comment]
Close (See the above comment URL)

**Comment by tillkolter** [comment]
I think this should not be closed, because there is a demand for this feature.

I ran into the same problem and could not even solve it as proposed in the above comment URL.
What helped me was this solution (constructing the string in a method, which seems pretty ugly to me 👎 ) https://forum-archive.vuejs.org/topic/3870/srcset-binding/3

**Comment by andelar** [comment]
Definitely should re-open. Any page gets a penalty on Google PageSpeed if not including the 1x size image, while almost all user devices today are 2x. So right now there is no acceptable solution to include images in Vue...

**Comment by AndreKR** [comment]
Absolutely. There is no reason vue-loader should treat `src` special but not `srcset`.

**Comment by AndreKR** [comment]
I made a PR. (#953)
