### ISSUE TITLE
Build component background-image path error

### ISSUE THREAD

**Issue by WangShayne** [vuejs/vue-loader#707]
```
build: {
    env: require('./prod.env'),
    index: path.resolve(__dirname, '../dist/index.html'),
    assetsRoot: path.resolve(__dirname, '../dist'),
    assetsSubDirectory: 'static',
    assetsPublicPath: './',
    productionSourceMap: false,
    productionGzip: false,
    productionGzipExtensions: ['js', 'css']
  },
```
output
```
output: {
    path: config.build.assetsRoot,
    publicPath: process.env.NODE_ENV === 'production' ? config.build.assetsPublicPath : config.dev.assetsPublicPath,
    filename: '[name].js'
  },
```
css
```
background: url(~assets/btn_my.png)
```
After build

![image](https://cloud.githubusercontent.com/assets/17644818/23788057/dceef028-05af-11e7-9ef5-ca9fc98df6fc.png)
But the other page work normal,like this
![image](https://cloud.githubusercontent.com/assets/17644818/23788081/f95003b0-05af-11e7-8d83-3c6c655f6459.png)
the component lose "./",the path change to "dist/static/css/static/img/xx.png"

**Comment by LinusBorg** [comment]
CSS doesn't need `./`. A path starting without a slash `/` *is* a relative path.

Your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests (as outlined in our [Contributing Guide](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md)).

So if you need further assistance with this problem, we encourage you to ask it on the [forum ](http://forum.vuejs.org) , [Stack Overflow](http://stackoverflow.com/questions/tagged/vue.js) or on [gitter](http://gitter.im/vuejs/vue) and are happy to help you out there.
