### ISSUE TITLE
Using state management with store pattern

### ISSUE THREAD

**Issue by cansuB** [vuejs/vue-loader#712]
Hi,

This is the example I follow https://jsfiddle.net/hr4mqhhe/ to have shared store object. Only difference is I am using vue-loader in Laravel. 

When I try to access to the store element in one of my components, I get 'Store is not defined' error. 

shared-state.js
```
let Store = {
    state: {
        theDateOnMap: '', // the time and date overlay on the map
    }
};
```

OpenLayersMap.vue
```
<template>
    <div class="row section-map" v-cloak>
        <div id="map" class="smallmap">
        </div>
    </div>
</template>
<script>
    export default {
        data(){
            return {
               sharedState: Store.state   
            }
        },
        mounted() {
            this.$on('loadMap', this.loadMap);
       
        },
        methods: {  
  loadMap() {}
}
    }
</script>
```

And this is the main app.js 

```
require('./vue-resource.min');
require('./store/shared-state');

Vue.component('ol-map', require('./components/OpenLayersMap.vue'));
//loading other components here 
new Vue({
    el: '#home-map'
})
```

Any help is appreciated

thanks

**Comment by LinusBorg** [comment]
Hello @cansuB 

Thank your for your interest in this project.

However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests (as outlined in our [Contributing Guide](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md)).

We encourage you to ask it on the [forum ](http://forum.vuejs.org), [Stack Overflow](http://stackoverflow.com/questions/tagged/vue.js) or on [gitter](http://gitter.im/vuejs/vue) and are happy to help you out there.
