### ISSUE TITLE
How to not compile ES6 codes?

### ISSUE THREAD

**Issue by weizhenye** [vuejs/vue-loader#713]
I'm using Vue to write an Electron App, so I don't need to compile ES6 to ES5, however I find scripts in `.vue` file are default compiled by `vue-template-es2015-compiler`, which is using bublé.

There're some bugs with bublé, for example:

```js
[...new Set([1,1,2,3])]
```

are compiled to

```js
[].concat( new Set([1,1,2,3]) )
```

that's a wrong result.

I know I can use babel to replace it, but what I actually want is do not compile ES6 codes. Is there any way to configure it?

**Comment by LinusBorg** [comment]
Hello @weizhenye 

Thank your for your interest in this project.

However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests (as outlined in our [Contributing Guide](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md)).

We encourage you to ask it on the [forum ](http://forum.vuejs.org) , [Stack Overflow](http://stackoverflow.com/questions/tagged/vue.js) or on [gitter](http://gitter.im/vuejs/vue) and are happy to help you out there.
