### ISSUE TITLE
Unable to use Less plugins

### ISSUE THREAD

**Issue by Justineo** [vuejs/vue-loader#716]
Less plugins are passed through unserializable options (plugin instances with `install` method), which will be ignored after `JSON.stringify`.

**Comment by LinusBorg** [comment]
We are aware of this. To make this possible we would have to rewrite quite a big part of core vue-loader functionality, especially if we intend to keep vue-loader webpack1 compatible.

This makes it unlikely to be fixed in the near future, but will probably be possible sometime.

I will close this issue as it is already on our radar and can't be fixed now.

Thanks for reporting it!
