### ISSUE TITLE
css中文转义的bug？

### ISSUE THREAD

**Issue by radius-yf** [vuejs/vue-loader#717]
我在vue文件中设置了CSS
```
font-family: "微软雅黑";
```
用webpack-dev-server启动后查看设置的属性是
```
font-family: "\5FAE\8F6F\96C5\9ED1";
```
但是编译之后再打开变成了
```
font-family: \\5FAE\8F6F\96C5\9ED1;
```
多了一个反斜杠，导致字体设置失败

请问有人遇到过这个问题吗？

webpack配置如下
```
	module: {
		rules: [
			{
				test: /\.vue$/,
				loader: 'vue-loader',
				options: {
					loaders: {
						// Since sass-loader (weirdly) has SCSS as its default parse mode, we map
						// the "scss" and "sass" values for the lang attribute to the right configs here.
						// other preprocessors should work out of the box, no loader config like this necessary.
						'scss': 'vue-style-loader!css-loader!sass-loader',
						'sass': 'vue-style-loader!css-loader!sass-loader?indentedSyntax'
					}
					// other vue-loader options go here
				}
			},
			{
				test: /\.js$/,
				loader: 'babel-loader',
				exclude: /node_modules/
			},
			{
				test: /\.css$/,
				loader: 'style-loader!css-loader'
			},
			{
				test: /\.(scss|sass)/,
				loader: 'style-loader!css-loader!sass-loader'
			},
			{
				test: /\.(mp3|png|jpg|gif|svg)$/,
				loader: 'url-loader',
				options: {
					limit: 4096
				}
			}
		]
	},
```

**Comment by lookas2001** [comment]
Use English, please.

**Comment by k186** [comment]
你确定不能用？那个编码是正确的，这个问题可以关闭了。不知道你自己尝试启动过打包后的文件没有。我测试过是没问题的显示正确。那个本来就是为了稳妥进行的转化。

**Comment by 409915016** [comment]
This seems to be caused by minimize CSS, check webpack config in your project.
try commond "npm run dev", the font-family Unicode encode is normal ?
Did your require or import CSS file from JS file? I think"webpack -p" not just minimize JS file.

1. Replace your font name , `微软雅黑` replace with `\5FAE\8F6F\96C5\9ED1`.
2.  Add `@charset "utf-8";` in your CSS file to keep UTF-8 encode, then the browser will parse normal.
(css file method, have JS file method ? Search in Google)

---
Chinese:
1. 尝试用 Unicode 编码来代替中文。
2. 在你的 CSS 文件中加入  `@charset "utf-8";` 来强制告诉浏览器该文件的编码。

reference:
[http://www.voidcn.com/blog/zgrbsbf/article/p-6231722.html](http://www.voidcn.com/blog/zgrbsbf/article/p-6231722.html)
[https://github.com/mishoo/UglifyJS2/issues/54#issuecomment-26230544](https://github.com/mishoo/UglifyJS2/issues/54#issuecomment-26230544)

**Comment by lizhaohuiGit** [comment]
> Use English, please.

right answer
