### ISSUE TITLE
Problem in conjunction with electron

### ISSUE THREAD

**Issue by raultrysw** [vuejs/vue-loader#752]
Hi, I am writting an application with electron and when i write style in a vue file this style not loads in the app on electron, however, if that style, I write in other file, the css loads correctly.
I am using sass, i don't know why is it, please help =)

**Comment by LinusBorg** [comment]
Hello @raultrysw 

Thank your for your interest in this project.

However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests (as outlined in our [Contributing Guide](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md)).

We encourage you to ask it on the [forum ](http://forum.vuejs.org) , [Stack Overflow](http://stackoverflow.com/questions/tagged/vue.js) or on [gitter](http://gitter.im/vuejs/vue) and are happy to help you out there.
