### ISSUE TITLE
how to import external CSS and js file in index.html weboack

### ISSUE THREAD

**Issue by jagasan** [vuejs/vue-loader#763]
hi 
i am try to include external css and js filein  webpack but unable to load js and css but 404 error are gerneate
because it append url in css  link and js script
like

GET http://localhost:8080/assestes/css/mystyle.css

**Comment by LinusBorg** [comment]
Hello jagasan, 

Thank your for your interest in this project.

However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests (as outlined in our [Contributing Guide](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md)).

We encourage you to ask it on the [forum ](http://forum.vuejs.org) , [Stack Overflow](http://stackoverflow.com/questions/tagged/vue.js) or on [gitter](http://gitter.im/vuejs/vue) and are happy to help you out there.
