### ISSUE TITLE
Vue property not available in data function

### ISSUE THREAD

**Issue by Mawalu** [vuejs/vue-loader#768]
### Version
11.0.0

### Reproduction link
[https://github.com/Mawalu/vue-i18n-bug-reproduction](https://github.com/Mawalu/vue-i18n-bug-reproduction)

### Steps to reproduce
Open the demo and look at the console

### What is expected?
`this.$t()` should be a function provided by vue-i18n

### What is actually happening?
`this.$t()` is undefined if used in the `data` function but works in event handler functions.

---
This issue was opened here kazupon/vue-i18n#108 and the vue-i18n maintainer @kazupon said it looks like a bug in vue-loader.

After I ran into this bug I forked @leo108 reproduction repo and created this issue.

**Comment by LinusBorg** [comment]
Please see my comments in the other issue. This seems like a module import mismatch, not a problem with vue-loader.

If you can change the reproduction to remove the things I mention and still reproduce the issue, we can consider re-opening this here. close until then.

**Comment by Mawalu** [comment]
I already removed the additional script tag that loads `vue.min.js` in my fork (the one that is linked above) so that only the webpack build file is loaded. Please correct my if I missed something

**Comment by LinusBorg** [comment]
Ah, my bad, I thought you were talking about the same issue as the OP in the issue you linked to, but your problem is something else.

But your case  is not a bug either:

* $t is added via a global mixin as a new computed property. 
* But during the bootstrap fo the component instance, $option.data is evaluated *before* the $options.computed:

https://github.com/vuejs/vue/blob/dev/src/core/instance/state.js#L48-L53

So this should rather be solved in Vue-i18n. Shouldn't you be able to use [`VueI18n.t()`](https://github.com/kazupon/vue-i18n/blob/dev/src/index.js#L196)?

**Comment by Mawalu** [comment]
Thanks for the explanation. I understand and agree that this is the expected behaviour from vue-loader.
