### ISSUE TITLE
When multiple components use the same script file the wrong component gets loaded when used as a route

### ISSUE THREAD

**Issue by berndderidder** [vuejs/vue-loader#779]
### Version
11.0.0

### Reproduction link
[https://github.com/berndderidder/vue-issue-repro](https://github.com/berndderidder/vue-issue-repro)

### Steps to reproduce
1. Create multiple .vue components and each of them uses the same script file via a src import
2. Create a route for each component
3. Visit each route

### What is expected?
Each route should show the correct component.

### What is actually happening?
If you visit each route you will see that each route shows the last loaded component with the src import.

---
This doesn't happen if for example each component has there own script file.

**Comment by LinusBorg** [comment]
This is expected behaviour. vue-loader does not duplicate the imported code from that script file, it imports it as a normal module, so all components using it subsequently override its render function.

To re-use shared functionality, you should use [mixins](https://vuejs.org/v2/guide/mixins.html#Basics) or [extend](https://vuejs.org/v2/api/#extends).
