### ISSUE TITLE
用webpack如何配置才可以过滤制表符和空格,是代码最大化压缩?

### ISSUE THREAD

**Issue by leyec** [vuejs/vue-loader#783]
### What problem does this feature solve?
t._v('\n\t\t\t\t\t\t\t喜欢('   t._s(e.likes_count)   ')\n\t\t\t\t\t\t')])])])])])])
生产环境压缩后还有很多\n\t保留,怎么办? 下面是我的webpack配置,帮忙看看哪里错了,这个问题困扰了好久了

### What does the proposed API look like?
rules: [{
			enforce: 'pre',
			test: /.vue$/,
			loader: 'eslint-loader',
			exclude: /node_modules/
		}, {
			test: /\.vue$/,
			loader: 'vue-loader',
			exclude: /node_modules/,
			options: {
				loaders: {
					js: 'babel-loader'
				},
				html: {
					collapseWhitespace: true,
					collapseInlineTagWhitespace: true
				},
				preserveWhitespace: false
			}
		}]

**Comment by LinusBorg** [comment]
Hello @leyec 

Thank your for your interest in this project.

However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests (as outlined in our [Contributing Guide](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md)).

We encourage you to ask it on the [forum ](http://forum.vuejs.org) , [Stack Overflow](http://stackoverflow.com/questions/tagged/vue.js) or on [gitter](http://gitter.im/vuejs/vue) and are happy to help you out there.
