### ISSUE TITLE
Problem trying to put custom path for postcss config file

### ISSUE THREAD

**Issue by jlpjavi** [vuejs/vue-loader#816]
I've the postcss working but I need to move the postcss.config.js from the root of the project to another config folder.

I've been trying several options specifying the path of the configuration file but none of them worked. Currently I have this in my webpack.config.js:

<code>
{
        test: /\.vue$/,
        loader: "vue-loader",
        options: {
          postcss: {
            config: {
              path: path.join(__dirname, './postcss.config.js'),
              ctx: { browsers }
            }           
          }
        }                
 }, 

</code>

**Comment by francoisromain** [comment]
Maybe, don't just link to `postcss.config.js`. You need to `require` the file.

**Comment by rascode** [comment]
Same issue here...

**Comment by rascode** [comment]
@jlpjavi , 

Just cracked the code on this one.  Instead of feeding your "config" object a "path" object that contains the path to your config file, simply declare the path to your config file in your "config" object.  For example.

## Old Code

`{
  loader: 'postcss-loader',
  options: {
    config: {
      path: 'path/to/postcss.config.js'
    }
  }
}`

## New Code
`{
  loader: 'postcss-loader',
  options: {
    config: 'path/to/postcss.config.js'
  }
}`


It makes more sense now that the compiler was complaining about wanting a string when we were both feeding it an object that contained a string. The official [postcss config documentation](https://github.com/postcss/postcss-loader#path) should be updated to reflect the proper configuration.  

I'm going to open a pull request to prevent others from pulling their hair out, but hope this helps you in the meantime. 

Cheers, 
Justin

**Comment by jlpjavi** [comment]
Thank you @rascode!
I've fixed the problem with your solution so I'm closing the issue
