### ISSUE TITLE
keyframes scoped but animation name not changed to v-xxx 

### ISSUE THREAD

**Issue by hoang17** [vuejs/vue-loader#842]
### Version
12.2.0

### Reproduction link
[https://github.com/PeachScript/vue-infinite-loading/blob/master/src/styles/spinner.less](https://github.com/PeachScript/vue-infinite-loading/blob/master/src/styles/spinner.less)

### Steps to reproduce
if animation name is not the first style value example:

animation: linear loading-rotating .85s infinite

then it is not changed to loading-rotating-data-v-xxxx

### What is expected?
animation name changed to loading-rotating-data-v-xxxx

### What is actually happening?
animation name still loading-rotating

---

**Comment by winghouchan** [comment]
Problem occurs due to how animation name parsing is handled. As of 47c3317 the animation name in shorthand animation rule declarations are identified by splitting the declaration value using any whitespace as the separator and assuming the first value is the animation name. https://github.com/vuejs/vue-loader/blob/47c33170986df96799d8fc4763671b6d926462f5/lib/style-compiler/plugins/scope-id.js#L66-L67

However CSS specification for the animation shorthand property states that the animation name could appear in any position within the rule declaration.

> `'<single-animation>' = <time> || <single-timing-function> || <time> || <single-animation-iteration-count> || <single-animation-direction> || <single-animation-fill-mode> || <single-animation-play-state> || [ none | <keyframes-name> ]`

– https://drafts.csswg.org/css-animations/#typedef-single-animation

**Comment by yyx990803** [comment]
fixed in 47c3317

**Comment by winghouchan** [comment]
> fixed in 47c3317

Before people get lost, it's actually fixed in 6d3c5b2c6d9b4dd0f282c45e6a8d734ce38011ed
