### ISSUE TITLE
HMR triggers prop mutation warnings on .vue components

### ISSUE THREAD

**Issue by last-partizan** [vuejs/vue-loader#846]
### Version
12.2.1

### Reproduction link
[https://github.com/last-partizan/test-hmr-warning](https://github.com/last-partizan/test-hmr-warning)

### Steps to reproduce
```
git clone https://github.com/last-partizan/test-hmr-warning.git
cd test-hmr-warning
yarn
yarn dev
```
now look at the console

### What is expected?
There is no warning related to mutating props.

### What is actually happening?
There is warning about mutating props.

---
This is happened to me becouse i don't use default webpack config from vue-cli, and in the `alias` section i have `vue-standalone` instead of `vue$`.
Then i enabled HotModuleReplacement and noticed that my components triggers warning without reason.

For now i just fix my webpack config, but maybe you find out why there is this warnings. And put big red sign "please use `vue$` as alias in your webpack config"

**Comment by LinusBorg** [comment]
The usage of such an alias is briefly explained here: 

https://vuejs.org/v2/guide/installation.html#Runtime-Compiler-vs-Runtime-only

However we could maybe better explain why it's required, and why it has to be `'vue$'`. Will suggest that for the website.

HMR always uses `import Vue from 'vue'` internally when requiring Vue during module replacement. so when people import a different version, e.g. with `import Vue from 'vue.common.js'`, there are now essentially two versions of Vue in memory, and the hot updates won't have any of the plugins and extensions that you defined in your app.

So instead of doing `import Vue from 'vue.common.js'`, we have to use an alias, which makes both our app code and the HMR code load the same desired vue version whn we do `import Vue from 'vue'`.

Changing this alias to something different (like `vue-standalone`) will not have this effect because HMR will still do `import Vue from 'vue'`, so you still end up with two different builds in your app.
