### ISSUE TITLE
build files paths contain unnecessary "/"

### ISSUE THREAD

**Issue by mendiomon** [vuejs/vue-loader#849]
Because of that i get 404 errors when i open index.html. I guess webpack assumes my build is in my server root or something. For example this:
`<script type=text/javascript src=/static/js/manifest.17fc521051925a678a2c.js></script>`
must be change to this:
`<script type=text/javascript src=static/js/manifest.17fc521051925a678a2c.js></script>`

How do i config webpack to create correct paths?

**Comment by LinusBorg** [comment]
Hello @mendiomon 

Thank your for your interest in this project.

However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests (as outlined in our [Contributing Guide](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md)).

We encourage you to ask it on the [forum ](http://forum.vuejs.org) , [Stack Overflow](http://stackoverflow.com/questions/tagged/vue.js) or on [gitter](http://gitter.im/vuejs/vue) and are happy to help you out there.
