### ISSUE TITLE
Scoped style, is it possible to access the hash value in the script or template section?

### ISSUE THREAD

**Issue by kaijajan** [vuejs/vue-loader#851]
The scoped style generates a hash value to the Vue file.
And it works in template section.
However, what if adding a css class name into DOM elements dynamically (via javascript)
For instance, I would like to add some scoped class into document.querySelector('className').className
But the className accepted is unscoped value.
Is it possbile to access the scoped value generated by vue-loader in script section?

**Comment by nickmessing** [comment]
@kaijajan, find a way to do that in vue with `:class`, mutating Vue-generated DOM will not work anyway because vue uses virtual-DOM and your modifications will get reset after next Vue Tick.

If you want more information I recommend asking in [gitter](https://gitter.im/vuejs/vue) or [forum](https://forum.vuejs.org).

**Comment by LinusBorg** [comment]
There's no public API for this, only an internal one: `this.$options._scopeId`. Use at your own risk, it can break with any patch release as we follow semver.
