### ISSUE TITLE
Can't run unit test if .vue component template src refers to an external html file.

### ISSUE THREAD

**Issue by freewayz** [vuejs/vue-loader#854]
So i have a .vue component  and html file.
dashboard.vue
```javascript
<template src='./dashboard.html'></template>
<script>
export default {
  name: 'dashboard',
};
</script>
```
dashboard.html
```html
<div>
    Dashboard Page
</div>

```
So when i try to run ` npm run unit`, it fails to run test with error show below.
<img width="978" alt="screen shot 2017-06-22 at 2 07 35 pm" src="https://user-images.githubusercontent.com/8389340/27435531-59e1d654-5754-11e7-83d2-07ba5b6e5375.png">

Please any help on this.

**Comment by LinusBorg** [comment]
add a loader for `.html` files.

{
  test: /\.html$/,
  use: 'vue-html-loader' // already installed as it's a dependency of vue-loader
}

Also, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests (as outlined in our [Contributing Guide](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md)).

We encourage you to ask it on the [forum ](http://forum.vuejs.org) , [Stack Overflow](http://stackoverflow.com/questions/tagged/vue.js) or on [gitter](http://gitter.im/vuejs/vue) and are happy to help you out there.

**Comment by freewayz** [comment]
Ok thanks @LinusBorg, it worked.  I did ask on the question on gitter but no response
