### ISSUE TITLE
phpstorm syntax issue

### ISSUE THREAD

**Issue by RostyslavSh** [vuejs/vue-loader#919]
I downloaded vue.js plugin for phpstorm but i have issues with syntax highlighting (errors everywhere). What is the best way to setup workspace?

**Comment by LinusBorg** [comment]
Hello @RostyslavSh 

Thank your for your interest in this project.

However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests (as outlined in our [Contributing Guide](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md)).

We encourage you to ask it on the [forum ](http://forum.vuejs.org) , [Stack Overflow](http://stackoverflow.com/questions/tagged/vue.js) or on our [Discord chat](http://chat.vuejs.org) and are happy to help you out there.
