### ISSUE TITLE
Functional Components Full Support

### ISSUE THREAD

**Issue by miljan-aleksic** [vuejs/vue-loader#963]
### What problem does this feature solve?
Functional components are very adecuate solution in many situations but their syntax complexity is a entrance barier. JSX is good, but still doesn't solve as easily many situations where the template compiler shines.

I would like to know if this feature is at least considered as by issue #573 seems is not.

### What does the proposed API look like?
Same as the current one.

**Comment by LinusBorg** [comment]
It's actually being discussed here: https://github.com/vuejs/vue/issues/3977, but hasn't made that much progress because it requires quite some work to take the differences and limitations of functional components into account when creating the render function from a template.

I will close this as the core repo is the right place to work in this, because the template compiler lives there, not in vue-loader.
